FROM nginx
LABEL version=1.0.0
RUN apt update
RUN apt install -y git
RUN apt install -y nano
RUN rm -rf /usr/share/nginx/html
RUN mkdir /usr/share/nginx/html
RUN git clone https://github.com/hossain109/TPDevOps.git /usr/share/nginx/html

#Ajouter des arguments
ARG search_text
ARG replace_text
ARG path=/usr/share/nginx/html/index.html

RUN sed -i "s/${search_text}/${replace_text}/g" ${path} 

EXPOSE 80